#!/bin/sh
echo "Running pre-push checks..."

npm run format:check && npm run lint && npm run typecheck && npm run knip && npm run test

if [ $? -ne 0 ]; then
  echo "Pre-push checks failed. Push aborted."
  exit 1
fi
